<?php
	$amCatList = Doctrine::getTable('Model_Category')->getCatList();
   	ksort($amCatList);
   	
   	$oRequest = Zend_Controller_Front::getInstance()->getRequest();
    $snEditId = $oRequest->getParam('editid');
?>
<form method="post" enctype="multipart/form-data">
<table>
	<tr>
		<?php  if($snEditId): ?>
			<th>Edit Category</th>
		<?php else: ?>
			<th>Add Category</th>
		<?php endif;?>	
	</tr>
	<?php if(empty($snEditId)): ?>
	<tr>
		<td><?php echo $this->oAddCateFrom->cat_name->renderLabel(); ?></td>
		<td>
			<?php echo $this->snParentId;?>
			<select name="parentid">
				<option value="0">Select Category</option>
				<?php getContent($amCatList, $this->snParentId);?>
			</select>
		</td>
	</tr>
	<?php endif; ?>
	<tr>
	<td><?php echo $this->oAddCateFrom->name->renderLabel(); ?></td>
	<?php foreach ($this->asLanguageList as $ssLanguageList): ?>
		<td>
			<table>
				<tr>
					<td><?php echo $ssLanguageList['name']; ?></td>
				</tr>
				<tr>
					<td><?php $ssCatName = 'name_' . $ssLanguageList['lang']; echo $this->translate($this->oAddCateFrom->$ssCatName->renderErrors()); ?></td>
				</tr>
				<tr>
					<td><?php echo $this->oAddCateFrom->$ssCatName->renderViewHelper();?></td>
				</tr>	
			</table>
		</td>
	<?php endforeach;?>
	</tr>
	<tr>
		<td><?php echo $this->oAddCateFrom->image_name->renderLabel(); ?></td>
		<td><?php echo $this->oAddCateFrom->image_name->renderfile();?></td>
		<td><?php echo $this->oAddCateFrom->image_name->renderErrors(); ?></td>
	</tr>
	<tr>
		<td><?php echo $this->oAddCateFrom->is_active->renderLabel(); ?></td>
		<td><?php echo $this->oAddCateFrom->is_active->renderViewHelper();?></td>
	</tr>
	<tr>
		<td><?php if($snEditId) { ?><input id="editid" type="hidden" value="<?php echo $snEditId; ?>" name="editid"></td>
			<td><?php echo $this->oAddCateFrom->category_edit->renderViewHelper();?><?php echo $this->oAddCateFrom->category_reset->renderViewHelper();?></td>
		<?php } else { ?>
			<td><?php echo $this->oAddCateFrom->category_add->renderViewHelper();?><?php echo $this->oAddCateFrom->category_reset->renderViewHelper();?></td>		
		<?php } ?>
	</tr>
</table>
</form>
<?php
	
	function getContent($amCategories = array(), $snParentId = 0) {
		if ($amCategories) {
			foreach ($amCategories as $amCategory) {
				
				$ssCurrentLocale = Zend_Registry::get('Zend_Locale')->toString(); ?>
				<option value="<?php echo $amCategory['id']; ?>" <?php if($amCategory['id'] == $snParentId ) { echo "selected=selected"; } ?>>
					<?php echo str_repeat("&nbsp;", ($amCategory['level'] * 2) ) . $amCategory['Translation'][$ssCurrentLocale]['name']; ?>
				</option>
				<?php
				unset($amCategory['id'], $amCategory['level'], $amCategory['is_active'], $amCategory['parentid'], $amCategory['Translation']);
				getContent($amCategory, $snParentId);	
			}
		}
		
	}