<table width='100%' border='0'>	
	<tr>
		<td align="left"><?php echo "Welcome"; ?> <font color="red" weight="bold"> <?php echo $this->admin_name; ?></font></td>
		<td align="right">
			<a href="<?php echo $this->url(array('module'=>'admin','controller'=>'login','action'=>'changepassword'))?>/id/<?php echo $this->aid;?>">Change Password</a>&nbsp;&nbsp;
			<a href="<?php echo $this->url(array('module'=>'admin','controller'=>'login','action'=>'logout'))?>">Logout</a><br>
		</td>
	</tr>
</table>