<?php

/**
 * Model_Base_Pages
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property string $url
 * @property boolean $is_active
 * @property integer $ord
 * @property string $title
 * @property string $menu_name
 * @property string $content
 * @property string $meta_title
 * @property string $meta_keyword
 * @property string $meta_description
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Model_Base_Pages extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('pages');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('parent_id', 'integer', 10, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             'length' => '',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('ord', 'integer', 10, array(
             'type' => 'integer',
             'default' => 1,
             'length' => '10',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('menu_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('meta_title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('meta_keyword', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('meta_description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'menu_name',
              2 => 'content',
              3 => 'meta_title',
              4 => 'meta_keyword',
              5 => 'meta_description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}