<div id="inner">
	<div><?php echo $this->translate('Zend FrameWork Doctrine Demo');?></div>
<LINK REL="SHORTCUT ICON" HREF="/images/favicon.ico">
<?php
		//Create Session Namespace object & check if Session is Created or not
        $oNamespace = new Zend_Session_Namespace('sess_admin');        
        $ssLoginUserName = $oNamespace->__get('admin_name');
        $snAdminId = $oNamespace->__get('aid');
?>
<div id="top">
	<?php if(isset($ssLoginUserName) && (!empty($ssLoginUserName))): ?>
	<div id="profile-welcome" class="welcome">Welcome :</div>
    <div class="prowelcome" id="profile-top"><?php echo $ssLoginUserName; ?></div>
    <?php endif;?>
	<div id="protoprght">
	    <div id="profiletoprghtlft">
       	  <ul id="protopmenu">
       	  	<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <li><?php if(isset($ssLoginUserName) && (!empty($ssLoginUserName))): ?><a href="<?php echo $this->url(array('module'=>'admin','controller'=>'login','action'=>'logout'))?>" title="Logout">Log Out</a><?php endif;?></li>
            <li><?php echo $this->partial('partials/language.phtml');?></li>
   		  </ul>
        </div>
      </div>
</div>
<div id="logo-main">
	<div id="logo"><a href="#" title="Zend Common By Bhaskar"><img src="/images/logo.jpg" height="80px" width="257px"/></a></div>
</div>
    </div>
<!--close-header-->

<!--start-menu-->
	<div id="btn-main">
    <div id="btn-parent">
    	<div id="probtn-lft">
    		<?php if(isset($ssLoginUserName) && (!empty($ssLoginUserName))): ?>
        	<?php echo $this->partial('partials/_menu.phtml');?>
        	<?php endif;?>
        </div>
        </div>
	</div>
<!--close-button-->             
