<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?> 
<?php $amLangActiveList = Doctrine::getTable('Model_Language')->getActiveLanguageList(); ?>

<?php foreach($amLangActiveList as $key => $asActiveLanguage): ?>
	<a href="<?php echo $this->url(array('module'=> 'language','controller'=> 'index','action'=> 'changelanguage','lang' => $asActiveLanguage['lang']))?>"><img src="/upload/language/<?php echo $asActiveLanguage['flag']; ?>" width='20' height="20" title="<?php echo $this->translate("ttl_".$asActiveLanguage['name']); ?>"/></a>
<?php endforeach; ?>	
	