<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>
<?php $snIdLanguage = $oRequest->getParam('id');  ?>
<?php echo (isset($snIdLanguage) ? $this->headTitle('Edit-Language') : $this->headTitle('Add-Language')); ?>
<form name="addlanguage" method="post" enctype="multipart/form-data">
	<fieldset width="100%"><legend><?php echo (isset($snIdLanguage) ? "Edit Language" : "Add New Language"); ?></legend>
		<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" >
			<tr>
		       	<td>
		       		<table width="100%" border="0" cellpadding="2" cellspacing="1">
						<?php if(isset($snIdLanguage)): ?>
						<tr>
							<td class="tblrow" colspan="3"><input type="hidden" name="id" id="id" value="<?php echo $snIdLanguage; ?>"/></td>
						</tr>
						<?php endif; ?>	
						<tr>
							<?php echo $this->form->name->Value;?>
							<td class="tblrow"><?php echo strip_tags($this->form->name->renderLabel()); ?></td>
							<td class="tblrow">
								<div id="error"><?php echo strip_tags($this->form->name->renderErrors());	?></div>
								<?php echo $this->form->name->renderViewHelper();?>
								
							</td>
						</tr>
						
						<tr>
							<td class="tblrow"><?php echo strip_tags($this->form->lang->renderLabel()); ?></td>
							<td class="tblrow">
								<div id="error"><?php echo strip_tags($this->form->lang->renderErrors());	?></div>
								<?php echo $this->form->lang->renderViewHelper();?>
							</td>
						</tr>
						
					
						
						<?php if(!isset($snIdLanguage)): ?>
						<tr>
							<td class="tblrow"><?php echo strip_tags($this->form->is_default->renderLabel()); ?></td>
							<td class="tblrow"><?php echo $this->form->is_default->renderViewHelper();?></td>
						</tr>
						<?php endif; ?>
						
						<tr>
							<td class="tblrow"><?php echo strip_tags($this->form->is_active->renderLabel()); ?></td>
							<td class="tblrow"><?php echo $this->form->is_active->renderViewHelper();?></td>
						</tr>
								
						<tr>
							<td class="tblrow"><?php echo strip_tags($this->form->flag->renderLabel()); ?></td>
							<td class="tblrow">
								<div id="error"><?php echo strip_tags($this->form->flag->renderErrors());	?></div>
								<?php if(trim(!empty($this->ImageName))):?>
									<img src="/upload/language/<?php echo $this->ImageName; ?>" width="20" height="20"/><br/>
								<?php endif; ?>
								<?php echo $this->form->flag->renderfile(); ?>
							</td>
						</tr>
							
						<tr>
							<td></td>
							<td class="tblrow" >
								<input type="submit" name="submit" value="Save" class='but'>
								<input type="reset" name="cancel" value="Cancel" class='but' title="Cancel" onclick="javascript: location.href='/<?php echo $oRequest->getParam('module').'/index'; ?>'">
							</td>
						</tr>
					</table>
				</td>
		    </tr>	    
	 	</table>
 	</fieldset>
</form>
<script type="text/javascript">
	document.getElementById('name').focus();
</script>