<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>
<?php $snEditId = $oRequest->getParam('id'); ?>
<?php echo (isset($snEditId) ? $this->headTitle('Edit-Page') : $this->headTitle('Add-Page')); ?>
<?php $ssCurrentLocale = Zend_Registry::get('Zend_Locale')->toString(); ?>
<?php $asLanguageList = Doctrine::getTable('Model_Language')->getLanguageList();?>
<?php $snTotLang = count($asLanguageList); $snI = 0; $ssContentString = ''; $ssMetaDescriptionString ='';
      foreach($asLanguageList as $key => $amLanguage) { 
		$ssContentString .= 'site_pages_content_'.$amLanguage['lang'];
		$ssMetaDescriptionString .= 'site_pages_meta_description_'.$amLanguage['lang'];
		if ($snTotLang != ++$snI){
			$ssContentString .= ',';
			$ssMetaDescriptionString .= ',';
		}
	}
?>
<script type="text/javascript" src="/js/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript" src="/js/tiny_mce/plugins/tinybrowser/tb_tinymce.js.php"></script>
<script type="text/javascript">
tinyMCE.init({
  	mode: "exact",
    elements: "<?php echo $ssContentString; echo ','; echo $ssMetaDescriptionString; ?>",
    plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
  	theme: "advanced",
  	theme_advanced_toolbar_location:   "top",
    theme_advanced_toolbar_align:      "left",
    theme_advanced_statusbar_location: "bottom",
  	theme_advanced_path_location: "bottom",
  	//theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
	//theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
	//theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
	//theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,spellchecker,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,blockquote,pagebreak,|,insertfile,insertimage",
	theme_advanced_resizing : true,
	file_browser_callback : "tinyBrowser",
    relative_urls : false,
  	extended_valid_elements: "img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name]",
  	Template_external_list_url : "js/template_list.js",
	External_link_list_url : "js/link_list.js",
	External_image_list_url : "js/image_list.js",
	media_external_list_url : "js/media_list.js",
	tab_focus : ':prev,:next',
  	relative_urls: false,
  	debug: true
  });
  function fileBrowserCallBack(field_name, url, type, win) {
		// This is where you insert your custom filebrowser logic
		alert("Example of filebrowser callback: field_name: " + field_name + ", url: " + url + ", type: " + type);

		// Insert new URL, this would normaly be done in a popup
		win.document.forms[0].elements[field_name].value = "someurl.htm";
	}
</script>
<form name="addeditpage" method="post" enctype="multipart/form-data">
	<fieldset width="100%"><legend><?php echo (isset($snEditId) ? $this->translate("Edit Page") : $this->translate("Add New Page")); ?></legend>
		<table width="100%" border="0" align="center" cellpadding="10" cellspacing="10" >
			<tr>
				<td class="tblrow">Parent </td>
				<td class="tblrow"><?php echo $this->form->parent_id->renderViewHelper();?> </td>
			</tr>
			<tr>
				<td></td>
				<?php foreach($asLanguageList as $key => $amLanguage) : ?>
				<td>
					<div class="languages"><?php echo $this->translate($amLanguage['name']);?></div>
				</td>
				<?php endforeach;?>
			</tr>
			<tr>
				<td class="tblrow"><?php echo strip_tags($this->form->cn_title->renderLabel()); ?><span id="error">*</span></td>
				<?php foreach($asLanguageList as $key => $amLanguage) : ?>
				<?php $ssColmnName = 'site_pages_title_' . $amLanguage['lang']; ?>
				<td class="tblrow">				
					<div id="error"><?php echo $this->translate(strip_tags($this->form->$ssColmnName->renderErrors()));?></div>
					<?php echo $this->form->$ssColmnName->renderViewHelper();?>
				</td>
				<?php endforeach;?>
			</tr>
			
			<tr>
				<td class="tblrow"><?php echo strip_tags($this->form->menu_name->renderLabel()); ?><span id="error">*</span></td>
				<?php foreach($asLanguageList as $key => $amLanguage) : ?>
				<?php $ssColmnName = 'site_pages_menu_name_' . $amLanguage['lang']; ?>
				<td class="tblrow">				
					<div id="error"><?php echo $this->translate(strip_tags($this->form->$ssColmnName->renderErrors()));?></div>
					<?php echo $this->form->$ssColmnName->renderViewHelper();?>
				</td>
				<?php endforeach;?>
			</tr>
			
			<tr>
				<td class="tblrow"><?php echo $this->form->meta_title->renderLabel(); ?></td>
				<?php foreach($asLanguageList as $key => $amLanguage) : ?>
				<?php $ssColmnName = 'site_pages_meta_title_' . $amLanguage['lang']; ?>
				<td class="tblrow">				
					<div id="error"><?php echo $this->translate(strip_tags($this->form->$ssColmnName->renderErrors()));?></div>
					<?php echo $this->form->$ssColmnName->renderViewHelper();?>
				</td>
				<?php endforeach;?>
			</tr>
			
			<tr>
				<td class="tblrow"><?php echo $this->form->meta_keyword->renderLabel(); ?></td>
				<?php foreach($asLanguageList as $key => $amLanguage) : ?>
				<?php $ssColmnName = 'site_pages_meta_keyword_' . $amLanguage['lang']; ?>
				<td class="tblrow">				
					<div id="error"><?php echo $this->translate(strip_tags($this->form->$ssColmnName->renderErrors()));?></div>
					<?php echo $this->form->$ssColmnName->renderViewHelper();?>
				</td>
				<?php endforeach;?>
			</tr>
			
			<tr>
				<td class="tblrow"><?php echo $this->form->content->renderLabel(); ?></td>
				<?php foreach($asLanguageList as $key => $amLanguage) : ?>
				<?php $ssColmnName = 'site_pages_content_' . $amLanguage['lang']; ?>
				<td class="tblrow">				
					<div id="error"><?php echo $this->translate(strip_tags($this->form->$ssColmnName->renderErrors()));?></div>
					<?php echo $this->form->$ssColmnName->renderViewHelper();?>
				</td>
				<?php endforeach;?>
			</tr>
			
			<tr>
				<td class="tblrow"><?php echo $this->form->meta_description->renderLabel(); ?></td>
				<?php foreach($asLanguageList as $key => $amLanguage) : ?>
				<?php $ssColmnName = 'site_pages_meta_description_' . $amLanguage['lang']; ?>
				<td class="tblrow">				
					<div id="error"><?php echo $this->translate(strip_tags($this->form->$ssColmnName->renderErrors()));?></div>
					<?php echo $this->form->$ssColmnName->renderViewHelper();?>
				</td>
				<?php endforeach;?>
			</tr>
			
			<tr>
				<td class="tblrow"><?php echo strip_tags($this->form->url->renderLabel()); ?><span id="error">*</span></td>
				<td>
					<div id="error" class=""><?php echo $this->translate(strip_tags($this->form->url->renderErrors()));	?></div>
					<?php echo $this->form->url->renderViewHelper();?>
				</td>
			</tr>	
			
			<tr>
				<td class="tblrow"><?php echo $this->form->is_active->renderLabel(); ?></td>
				<td>
					<div id = "error"><?php echo strip_tags($this->form->is_active->renderErrors());?><div>
					<?php echo $this->form->is_active->renderViewHelper();?>
				</td>
			</tr>	
			
			<tr>
				<td><?php if(isset($snEditId)): ?><input type="hidden" name="id" id="id" value="<?php echo $snEditId; ?>" /><?php endif; ?></td>
				<td >
					<input type="submit" name="submit" value="Save" class='but'>
					<input type="reset" name="cancel" value="Cancel" class='but' title="Cancel" onclick="javascript: location.href='/<?php echo $oRequest->getParam('module').'/city'; ?>'">
				</td>
			</tr>
	 	</table>
 	</fieldset>	
</form>