<?php $this->headTitle()->append('Change Password'); ?>
<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>

<fieldset class="changepassFix"><legend><?php echo $this->translate("lbl_change_password"); ?></legend>
	<form class="login" name="changepass" method="post" action="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'changepasscheck'));?>">
		<table width="70%" border="0" align="center" cellpadding="0" cellspacing="0"  align="center">
	     	<tr>
				<td colspan="3" align="center" id="error" class="tblrow">
					<?php echo $this->translate(strip_tags($this->flashMessages()));?>
				</td>
			</tr>
			<tr>
				<td><input type="hidden" name="id" id="id" value="<?php echo $this->id ;?>"/></td>
			</tr>
			<tr>
				<td class="tblrow"><?php echo $this->translate(strip_tags($this->form->oldpassword->renderLabel())); ?><spn id="error">*</span></td>
				<td class="tblrow">
					<div id="error"><?php echo $this->translate(strip_tags($this->form->oldpassword->renderErrors()));?></div>
					<?php echo $this->form->oldpassword->renderViewHelper();?>
				</td>
			</tr>
			<tr>
				<td class="tblrow"><?php echo $this->translate(strip_tags($this->form->newpassword->renderLabel())); ?><spn id="error">*</span></td>
				<td class="tblrow">
					<div id="error"><?php echo $this->translate(strip_tags($this->form->newpassword->renderErrors()));?></div>
					<?php echo $this->form->newpassword->renderViewHelper();?>
				</td>
			</tr>
			<tr>
				<td class="tblrow"><?php echo $this->translate(strip_tags($this->form->confirmpassword->renderLabel())); ?><spn id="error">*</span></td>
				<td class="tblrow">
					<div id="error"><?php echo $this->translate(strip_tags($this->form->confirmpassword->renderErrors()));?></div>
					<?php echo $this->form->confirmpassword->renderViewHelper();?>
				</td>
			</tr>
			<tr>
				<td colspan="3" align="center" class="tblrow" >
					<input type="submit" class="but" name="Changepass" value="<?php echo $this->translate('btn_change_password')?>" title="<?php echo $this->translate("ttl_change_password"); ?>"/>
					<input type="reset" name="reset" value="<?php echo $this->translate('btn_cancel')?>" style="cursor: pointer;" title="<?php echo $this->translate("ttl_cancel"); ?>" onclick="javascript: location.href='/<?php echo $oRequest->getParam('module').'/index'; ?>'" class="but" />
				</td>
			</tr>
		</table>
	</form>
</fieldset>
<script type="text/javascript">
	document.getElementById('oldpassword').focus();
</script>