<?php $this->headTitle()->append('Change Password'); ?>
<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>
<fieldset width="100%"><legend>Change Password</legend>
<div id="content">
<form class="login" name="changepass" method="post" action="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'changepasscheck'));?>">
	<table width="40%" border="0" align="center" cellpadding="0" cellspacing="0" class="tblbg" align="center">
		<tr>
	       	<td>
	       		<table width="100%" border="0" cellpadding="2" cellspacing="1">
		        	<tr class="tblheader">
		            	 <td colspan="3">Change Password</td>
		         	</tr>
		         	
		         	<tr>
						<td colspan="3" align="center" id="error" class="tblrow">
							<?php echo "<font color='red'><b>".strip_tags($this->flashMessages())."</b></font>";?>
						</td>
					</tr>
					
					<tr>
						<td><input type="hidden" name="id" id="id" value="<?php echo $this->id ;?>"/></td>
					</tr>
					
					<tr>
						<td class="tblrow"><?php echo strip_tags($this->form->oldpassword->renderLabel()); ?></td>
						<td class="tblrow">
							<div id="error" class="tblrow"><?php echo strip_tags($this->form->oldpassword->renderErrors());?></div>
							<?php echo $this->form->oldpassword->renderViewHelper();?>
						</td>
					</tr>
					
					<tr>
						<td class="tblrow"><?php echo strip_tags($this->form->newpassword->renderLabel()); ?></td>
						<td class="tblrow">
							<div id="error" class="tblrow"><?php echo strip_tags($this->form->newpassword->renderErrors());?></div>
							<?php echo $this->form->newpassword->renderViewHelper();?>
						</td>
					</tr>
					
					<tr>
						<td class="tblrow"><?php echo strip_tags($this->form->confirmpassword->renderLabel()); ?></td>
						<td class="tblrow">
							<div id="error" class="tblrow"><?php echo strip_tags($this->form->confirmpassword->renderErrors());?></div>
							<?php echo $this->form->confirmpassword->renderViewHelper();?>
						</td>
					</tr>
					
					<tr>
						<td colspan="3" align="center" class="tblrow" >
							<input type="submit" class="but" name="Changepass" value="Change password" />
							<input type="reset" name="reset" value="Cancel" style="cursor: pointer;" title="Cancel" onclick="javascript: location.href='/<?php echo $oRequest->getParam('module').'/index'; ?>'" class="but" />
						</td>
					</tr>
				</table>
			</td>
	    </tr>
 	</table>
</form>
</div>
</fieldset>
<script type="text/javascript">
	document.getElementById('oldpassword').focus();
</script>