<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>
<?php $snIdVariable = $oRequest->getParam('id');  ?>
<?php echo (isset($snIdVariable) ? $this->headTitle('Edit-Variable') : $this->headTitle('Add-Variable')); ?>
<form name="addeditvariable" method="post" enctype="multipart/form-data">
	<fieldset>
		<legend><?php echo (isset($snIdVariable) ? $this->translate("Edit Variable") : $this->translate("Add New Variable")); ?></legend>
		<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" >
			<tr>
	      	 	<td>
					<table width="100%" border="0"  align="left">
						<tr>
							<td class=""><?php echo $this->translate(strip_tags($this->form->name->renderLabel())); ?><span id="error">&nbsp;*&nbsp;</span></td>
							<td>
								<div id="error"><?php echo $this->translate($this->translate(strip_tags($this->form->name->renderErrors())));?></div>
								<?php echo $this->form->name->renderViewHelper();?>
							</td>
						</tr>
						<?php $asLanguageList = Doctrine::getTable('Model_Language')->getLanguageList();	?>
						<tr>
							<td class=""><?php echo $this->translate("Value"); ?><span id="error">&nbsp;*&nbsp;</span></td>
							<?php foreach($asLanguageList as $key => $amLanguage) : ?>
							<?php $ssColmnName = 'value_' . $amLanguage['lang']; ?>
							<td>
								<table width="100%">
									<tr>
										<td class=""><?php echo $this->translate($amLanguage['name']);?></td>
									</tr>
									<tr>
										<td id="error"><?php echo $this->translate(strip_tags($this->form->$ssColmnName->renderErrors()));?></td>
									</tr>
									<tr>
										<td style="width:auto;"><?php echo $this->form->$ssColmnName->renderViewHelper();?></td>
									</tr>
								</table>				
							</td>
							<?php endforeach;?>
						</tr>
						<tr>
							<td class=""><?php echo strip_tags($this->form->is_active->renderLabel()); ?></td>
							<td class=""><?php echo $this->form->is_active->renderViewHelper();?></td>
							<td id="error" class=""><?php echo strip_tags($this->form->is_active->renderErrors());	?></td>
						</tr>				
						<tr>
							<td><?php if(isset($snIdVariable)): ?><input type="hidden" name="id" id="id" value="<?php echo $snIdVariable; ?>" /><?php endif; ?></td>
							<td >
								<input type="submit" name="submit" value="<?php echo $this->translate("Save"); ?>" class='but'>
								<input type="reset" name="cancel" value="<?php echo $this->translate("Cancel"); ?>" class='but' title="Cancel" onclick="javascript: location.href='/<?php echo $oRequest->getParam('module').'/index'; ?>'">
							</td>
						</tr>
					</table>		
				</td>
	    	</tr>	    
 		</table>
	</fieldset>	
</form>
<script type="text/javascript">
	document.getElementById('name').focus();
</script>