<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>
<fieldset ><legend><?php echo $this->translate("lbl_manage_variable")?></legend>
<table width='100%' border='0' >	
	<tr>
		<td align="center" colspan="8">
			<p><font color="#cd435d"><?php echo $this->translate(strip_tags($this->flashMessages())); ?></font></p>
		</td>
	</tr>
</table>
<div id="welcome">
	<?php echo $this->partial('partials/_navigation.phtml');?>
	<?php echo $this->partial('partials/_search.phtml',array('asSearchOption'=>$this->asSearchOption)); ?>
	<table border="0" width="100%">
		<tr>
			<td colspan="6" align="right" class="tblrow">
				<img src="/images/add.gif">&nbsp;<a href="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'addedit'));?>"><?php echo $this->translate("lnk_add_variable"); ?></a>&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'generatefile'));?>" class="but"><?php echo $this->translate("lnk_generate_file"); ?></a>
			</td>		
		</tr>
		<tr>
			<td>
				<?php echo $this->partial('partials/_list.phtml',array('asList'=>$this->user, 'asHeading'=>$this->asHeading, 'asFieldName'=>$this->asFieldName, 'asColumnSort'=>$this->asColumnSort, 'asColumnWidth'=>$this->asColumnWidth, 'asColumnAlign'=>$this->asColumnAlign));?>
			</td>
		</tr>
	</table>	
	<!-- Pagination Link Partial Set imageview = true to Show NEXT PREVIOUS Image & Need to giv folder name where images are  -->
	<?php echo $this->paginationControl($this->user, 'Sliding', 'partials/_pagination.phtml', array('searchSelect' => $this->ssSearchField, 'searchKeyword' => $this->ssSearchKeyword, 'imageview' => 'false')); ?>
</div>
</fieldset>
