<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>
<a href="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'addedit'));?>"><?php echo $this->translate('Add Variable');?></a>
<div>
	<div class="genratefile" align="right"><a href="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'generatefile'));?>"><?php echo $this->translate('Generate File'); ?></a></div>
<div>
	<div class="genratefile" align="right"></div>
</div>
<fieldset width="100%"><legend>Manage Variable</legend>
<table width='100%' border='0' >	
	<tr>
		<td align="center" colspan="8">
			<?php $messenger = Zend_Controller_Action_HelperBroker::getStaticHelper('FlashMessenger');
            $messages = array_merge($messenger->getCurrentMessages(),$messenger->getMessages());
            if( $messages != ""):
            foreach ($messages as $message) { ?>
               <p><font color="#cd435d"><?php echo $this->escape($message); ?></font></p>
            <?php }
            endif;
            $messenger->clearMessages(); ?>
		</td>
	</tr>
</table>
<div id="welcome">
	<?php echo $this->partial('partials/_navigation.phtml');?>
	<?php echo $this->partial('partials/_search.phtml',array('asSearchOption'=>$this->asSearchOption)); ?>
	<table border="0" width="100%">
		<tr>
			<td colspan="6" align="right" class="tblrow">
				<img src="/images/add.gif">&nbsp;<a href="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'addedit'));?>">Add Variable</a>&nbsp;&nbsp;&nbsp;&nbsp;
				<a href="<?php echo $this->url(array('module' => $oRequest->getParam('module'), 'controller' => $oRequest->getParam('controller'), 'action' => 'generatefile'));?>" class="but">Generate File</a>
			</td>		
		</tr>
		<tr>
			<td>
				<?php echo $this->partial('partials/_list.phtml',array('asList'=>$this->user, 'asHeading'=>$this->asHeading, 'asFieldName'=>$this->asFieldName, 'asColumnSort'=>$this->asColumnSort, 'asColumnWidth'=>$this->asColumnWidth, 'asColumnAlign'=>$this->asColumnAlign));?>
			</td>
		</tr>
	</table>	
	<!-- Pagination Link Partial Set imageview = true to Show NEXT PREVIOUS Image & Need to giv folder name where images are  -->
	<?php echo $this->paginationControl($this->user, 'Sliding', 'partials/_pagination.phtml', array('searchSelect' => $this->ssSearchField, 'searchKeyword' => $this->ssSearchKeyword, 'imageview' => 'false')); ?>
</div>
</fieldset>
