<?php 
	$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
	$this->headTitle()->setSeparator(' - ');
	$this->headTitle('ZEND COMMON PROJECT');
	$this->custom_head = '<script src="/js/fckeditor/fckeditor.js" type="text/javascript"></script>';
	$this->custom_head .= "<script language='javascript' type='text/javascript' src='/js/customs.js'></script>";
	$this->custom_body = ' onload="setupFCK()"';
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head> 
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css');?>
		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/pagelink.css');?>			
		<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/function.js'); ?>
		<!-- Include function file -->
		<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery.js'); ?>
		
	</head>
<body>
	<div id="header">
		<!--Header File -->
		<?php echo $this->partial('partials/_header.phtml'); ?>
	</div>
		<?php $oSession = new Zend_Session_Namespace('sess_admin'); ?>	
		<?php $ssSessionName =  $oSession->__get('admin_name'); ?>
	 <div id="breadcrumb">
     	<div id="breadcrumb-inner"><?php echo ($ssSessionName ? $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render() : ""); ?></div>
    </div>
	<div id="cnt-main" align="center">
		<h1><?php echo $this->escape($this->title); ?></h1>
			<?php echo $this->layout()->content; ?>
	</div>	
	<br/><br/>
	<div id="footer">
		<!--Footer File -->
		<?php echo $this->partial('partials/_footer.phtml'); ?>
	</div>
</body>
</html>