<?php
/**
 * Model_CountryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Application
 * @subpackage Model
 */
class Model_CountryTable extends Doctrine_Table
{
	/**
	* For Fetch All Record From Country Table
	*
	* @author Bhaskar joshi
	* @access public
	* @return array of Country table records 
	*/
	public function getCountryList($ssSortOn = '', $ssSortBy = '', $ssLang = 'en')
	{
		try
		{
			$oSelectQuery = Doctrine_Query::create();
			$oSelectQuery->select('C.id, C.is_active, T.*');
			$oSelectQuery->from("Model_Country C " );
			$oSelectQuery->leftjoin("C.Translation T");
			$oSelectQuery->andwhere("T.lang = ?", $ssLang);
			if( !empty($ssSortOn) && !empty($ssSortBy) )
				 $oSelectQuery->orderBy( $ssSortOn . ' ' . $ssSortBy );
	
			return $oSelectQuery->fetchArray();	

		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}	
	}
	
	/**
	* For Fetch Record of Given Country Id From Country Table
	*
	* @author Bhaskar joshi
	* @param  number $snCountryId for Country Id
	* @access public
	* @return array of Country table records 
	*/
	public function getCountryById($snCountryId ='')
	{
		if( $snCountryId == "" || !is_numeric($snCountryId) || $snCountryId == 0 ) return false;
		
		try
		{
			$oSelectQuery = Doctrine_Query::create();
			$oSelectQuery->select('C.*, T.*');
			$oSelectQuery->from("Model_Country C " );
			$oSelectQuery->leftjoin("C.Translation T");
			$oSelectQuery->where("C.id = ?", $snCountryId);
	
			return $oSelectQuery->fetchArray();
		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}
	}
	
	/**
	* For Insert Country data
	*
	* @author Bhaskar joshi
	* @access public
	* @param  array $asCountryData is form Data array
	* @return boolean
	*/
	public function InsertCountry($asCountryData = array())
	{
		if(!is_array($asCountryData) || empty($asCountryData)) return false;

		try
		{
			//Inserting Country Data into table
			$oCountry = new Model_Country();
			
			//Inserting Language wise country Name using foreach
			$asLanguageList = Doctrine::getTable('Model_Language')->getLanguageList();
			foreach($asLanguageList as $snKey => $amValues) 
			{
				 $oCountry->Translation[$amValues['lang']]->name = $asCountryData['name_' . $amValues['lang']];
			}
			$oCountry->is_active = $asCountryData['is_active'];
			$oCountry->created_at =  date('Y-m-d H:i:s');
			$oCountry->updated_at =  date('Y-m-d H:i:s');
			$oCountry->save();
			
			return true;
		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}
	}
	
	/**
	* For Update Country data
	*
	* @author Bhaskar joshi
	* @access public
	* @param  array $asCountryFormData is form Data array
	* @return boolean
	*/
	public function UpdateCountry($asCountryFormData = array())
	{
		if( !is_array( $asCountryFormData ) || empty( $asCountryFormData ) ) return false;
		
		try
		{   
			//Update Country Table
			$oUpdateCountry = Doctrine::getTable('Model_Country')->find($asCountryFormData['id']);			
			$oUpdateCountry->set("is_active", $asCountryFormData['is_active']);
			$oUpdateCountry->set("updated_at", date('Y-m-d H:i:s'));
						
			//Updateing Transaction Table 
			$asLanguageList = Doctrine::getTable('Model_Language')->getLanguageList();
			foreach($asLanguageList as $snKey => $amValues) {
				$oUpdateCountry->Translation[$amValues['lang']]->name = $asCountryFormData['name_' . $amValues['lang']];
			}			
			$oUpdateCountry->save();
			return true;
		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}
	}
	
	/**
	* For Delete Country Record From Table
	*
	* @author Bhaskar joshi
	* @access public
	* @param  $snCountryId for Which Country Id is Delete
	* @return boolean
	*/
	public function deleteCountry($snCountryId = 0)
	{
		if( $snCountryId == "" || !is_numeric($snCountryId) || $snCountryId == 0 ) return false;
		try
		{
			//delete data from Varible table
			Doctrine_Query::create()
						->delete("Model_Country C")
						->where("C.id = ?", $snCountryId)
						->execute();
			return true;
		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}		
	}
	
	/**
	* For Enable Or Disable Country
	*
	* @author Bhaskar joshi
	* @access public
	* @param  number  $snCountryId is id of Country to set Enable or Disable
	* @param  boolean $b__isActive for check the value of is_active on click
	* @return boolean
	*/
	public function changeEnableDisable($snCountryId = '', $bIsActive = 0)
	{
		if((empty($snCountryId) && empty($bIsActive)) || !is_numeric($snCountryId) || $snCountryId == 0 ) return false;
		
		try
		{
			//change the value of is_active of Given Row Id
			$bIsActive = ($bIsActive) ? 0 : 1;
			
			//Update Country table
			$asLanguageUpdate = Doctrine_Query::create()
					->update("Model_Country C")
					->set("C.is_active", "?", $bIsActive)
					->set("updated_at", "?", date('Y-m-d H:i:s'))
					->where("C.id = ?", $snCountryId)
					->execute();
			return true;
		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}		
	}
}