<?php
/**
 * Model_SitePagesTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Application
 * @author     Bhaskar Joshi
 * @subpackage Model
 */
class Model_SitePagesTable extends Doctrine_Table
{
	/**
	* For Fetch All Record From site_pages Table
	*
	* @author Bhaskar joshi
	* @access public
	* @return array of site_pages table records 
	*/
	public function getSitePagesList($ssSortOn = '', $ssSortBy = '', $ssSearchField = '', $ssSearchKeyword = '', $ssLang = 'en')
	{
		try
		{
			$oSelectQuery = Doctrine_Query::create();
			$oSelectQuery->select('S.*, T.*');
			$oSelectQuery->from("Model_SitePages S" );
			$oSelectQuery->leftjoin("S.Translation T");
			$oSelectQuery->andwhere("T.lang = ?", $ssLang);
			if( !empty($ssSearchField) && !empty($ssSearchKeyword) )
				$oSelectQuery->where($ssSearchField . " LIKE '" . $ssSearchKeyword . "%'" );
		
			if( !empty($ssSortOn) && !empty($ssSortBy) )
				 $oSelectQuery->orderBy( $ssSortOn . ' ' . $ssSortBy );
	
			return $oSelectQuery->fetchArray();	

		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}	
	}
}