<?php
 /**
 * Model_AdminTable
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Bhaskar Joshi
 * @package    Application
 * @subpackage Model
 */
class Model_AdminTable extends Doctrine_Table
{
	/**
	* For Fetch Record From Table By Given ID
	*
	* @author Bhaskar joshi
	* @param number $snAdminId for Admin Id
	* @access public
	* @return array 
	*/
	public function getAdminRecordById($snAdminId = '')
	{
		if( empty($snAdminId) || !is_numeric($snAdminId) ) return false;
		
		try
		{
			$oAdmin = Doctrine_Query::create()
					->select("*")
					->from("Model_Admin A")
					->where("A.id = ?", $snAdminId);
			
			return ($oAdmin) ? $oAdmin->fetchOne()->toArray() : false;				
		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}
	}
	
	/**
	* For Change Admin Password
	*
	* @author Bhaskar joshi
	* @access public
	* @param  mixed $smPassword To for new Password
	* @param  number $snAdminId for admin Id 
	* @return boolean
	*/
	public function changeAdminPassword($smPassword = '',$snAdminId = '')
	{
		if(empty($smPassword) || empty($snAdminId) || is_array($snAdminId) || !is_numeric($snAdminId)) return false;

		try
		{
			$oAdmin = Doctrine_Query::create()
					->update("Model_Admin A")
					->set("A.password", "?", $smPassword)
					->set("A.updated_at","?", date('Y-m-d H:i:s'))
					->where("A.id = ?", $snAdminId)
					->execute();
					
			return ($oAdmin) ? true : false;
		}
		catch( Exception $oException )
		{
			echo $oException->getMessage();
			return false;
		}
	}
}