<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>
<?php $snIdVariable = $oRequest->getParam('id'); ?>
<?php echo (isset($snIdVariable) ? $this->headTitle('Edit-Country') : $this->headTitle('Add-Country')); ?>

<form name="addeditcountry" method="post" enctype="multipart/form-data">
	<fieldset><legend><?php echo (isset($snIdVariable) ? "Edit Country" : "Add New Country"); ?></legend>
		<table width="80%" border="0" align="center" cellpadding="0" cellspacing="0" >
			<tr>
		       	<td>
		       		<table width="100%" border="0" cellpadding="2" cellspacing="1">
						<?php $asLanguageList = Doctrine::getTable('Model_Language')->getLanguageList();	?>
						<tr>
							<td class="tblrow">Name *</td>
							<?php foreach($asLanguageList as $key => $amLanguage) : ?>
							<?php $ssColmnName = 'name_' . $amLanguage['lang']; ?>
							<td class="tblrow">
								<div ><?php echo $amLanguage['name'];?></div>
								<div ><?php echo strip_tags($this->form->$ssColmnName->renderErrors());?></div>
								<div><?php echo $this->form->$ssColmnName->renderViewHelper();?></div>
							</td>
							<?php endforeach;?>
						</tr>
						<tr>
							<td class="tblrow"><?php echo strip_tags($this->form->is_active->renderLabel()); ?></td>
							<td class="tblrow"><?php echo $this->form->is_active->renderViewHelper();?></td>
							<td id="error" class="tblrow"><?php echo strip_tags($this->form->is_active->renderErrors());	?></td>
						</tr>				
						<tr>
							<td class="tblrow"><?php if(isset($snIdVariable)): ?><input type="hidden" name="id" id="id" value="<?php echo $snIdVariable; ?>" /><?php endif; ?></td>
							<td class="tblrow">
								<input type="submit" name="submit" value="Save" class='but'>
								<input type="reset" name="cancel" value="Cancel" class='but' title="Cancel" onclick="javascript: location.href='/<?php echo $oRequest->getParam('module').'/country'; ?>'">
							</td>
						</tr>
					</table>
				</td>
		    </tr>	    
	 	</table>
 	</fieldset>
</form>