<div class="mainmenu">
	<div class="menutitle"><a href="#">Home</a></div>
	<div class="menutitle"><a href="#">Country</a></div>
	<div class="menutitle"><a href="#">City</a></div>
	<div class="menutitle"><a href="category/index/listcategory">Category</a></div>
	<div class="menutitle"><a href="language/index/index">language</a></div>
	<div class="menutitle"><a href="#">Variable</a></div>
	<div class="menutitle"><a href="#">Products</a></div>
	<div class="menutitle"><a href="#">Keywords</a></div>
	<?php echo $this->ssLoginUserName;?>
	<div class="menutitle"><a href="#">Reset Password</a></div>
</div>
	
