<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>

<table border="0" width="100%" class="tblbg">
	<tr>
	<?php foreach($this->asHeading as $snKey => $ssHeading): ?>
		<th align="<?php echo $this->asColumnAlign[$snKey]; ?>" width="<?php echo $this->asColumnWidth[$snKey]; ?>" class="tblheading">
		<?php if(count($this->asList) > 0): ?>
			<?php if ($this->asColumnSort[$snKey]): ?>
				<a href="<?php echo $this->url(array('searchSelect' => $oRequest->getParam('searchSelect'), 'searchKeyword' => $oRequest->getParam('searchKeyword'), 'sortOn' => $this->asFieldName[$snKey], 'sortBy' => (($oRequest->getParam('sortOn') == $this->asFieldName[$snKey]) ? (($oRequest->getParam('sortBy') == 'ASC') ? 'DESC' : 'ASC') : 'DESC')));?>">
				<?php $imageName = (($oRequest->getParam('sortOn') == $this->asFieldName[$snKey]) ? (($oRequest->getParam('sortBy') == 'DESC') ? "ASC.png" : "DESC.png")  : "DESC.png"); ?>
				<?php echo $this->translate($ssHeading) ?></a> <img src="/images/<?php echo $imageName; ?>" style="border:0" height="8" width="8" alt="sorting" />
			<?php else: ?>
				<?php echo $this->translate($ssHeading) ?>
			<?php endif; ?>
		<?php else: ?>
			<?php echo $this->translate($ssHeading); ?>
		<?php endif; ?>
		</th>
	<?php endforeach; ?>
	</tr>
	<?php if( count( $this->asList ) > 0 ): ?>
	<?php foreach($this->asList as $asList): ?>
	<tr>
	<?php foreach($this->asFieldName as $snKey => $ssFieldName): ?>
		<td align="<?php echo $this->asColumnAlign[$snKey]; ?>" class="tblrow">
				<?php echo (!empty($ssFieldName)) ? $asList[$ssFieldName] : $asList[$snKey] ; ?>
		</td>
	<?php endforeach; ?>			
	</tr>
	<?php endforeach; ?>
	<?php else: ?>
	<tr>
		<th colspan="<?php echo count( $this->asHeading );?>" class="tblrow"><?php echo $this->translate("No record found"); ?></th>
	</tr>
	<?php endif;?>
</table>