<?php $oRequest = Zend_Controller_Front::getInstance()->getRequest(); ?>

<?php if ($this->pageCount > 1): ?>
	<!-- Previous page link -->
	<table id="maindiv">
		<tr  class="pagination" >
			<td id="inner">
				<?php if (isset($this->previous)): ?>
					<?php if($this->imageview == "true"): ?>
						<a id="pg_first" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $this->first)); ?>" title="first"><img src="/images/pag-first-icon.gif" /></a>
						<a id="pg_previous" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword,'page' => $this->previous)); ?>" title="previous"><img src="/images/pag-pre-icon.gif" /></a>
					<?php else: ?>
						<a id="pg_first" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $this->first)); ?>" title="first"><?php echo $this->translate('First'); ?></a>
						<a id="pg_previous" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $this->previous)); ?>" title="previous"><?php echo $this->translate('Previous'); ?></a>
					<?php endif; ?>
					
				<?php else: ?>
					<span class="disabled"><?php echo $this->translate('First'); ?></span>
					<span class="disabled"><?php echo $this->translate('Previous'); ?></span>
				<?php endif; ?>
			</td>
			<td id="inner">
				<!-- Numbered page links -->
				<?php foreach ($this->pagesInRange as $page): ?>
					<?php if ($page != $this->current): ?>
						<a id="pg_number" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $page)); ?>" title="<?php echo $page?>"><?php echo $page; ?></a> 
					<?php else: ?>
						<span class="current"><?php  echo $page; ?></span>
					<?php endif; ?>
				<?php endforeach; ?>
			</td>
			<td>
				<!-- Next page link -->
				<?php if (isset($this->next)): ?>
					<?php if($this->imageview == "true"): ?>
						<a id="pg_next" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $this->next)); ?>" title="next"><img src="/images/pag-next-icon.gif" /></a>
						<a id="pg_last" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $this->last)); ?>" title="last"><img src="/images/pag-last-icon" /></a>
					<?php else: ?>
						<a id="pg_next" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $this->next)); ?>" title="next"><?php echo $this->translate('Next'); ?></a>
						<a id="pg_last" href="<?php echo $this->url(array('searchSelect' => $this->searchSelect, 'searchKeyword' => $this->searchKeyword, 'page' => $this->last)); ?>" title="last"><?php echo $this->translate('Last'); ?></a>					
					<?php endif; ?>
				<?php else: ?>
					<span class="disabled"><?php echo $this->translate('Next'); ?></span>
					<span class="disabled"><?php echo $this->translate('Last'); ?></span>
				<?php endif; ?>
			</td>
		</tr>
	</table>
<?php endif;?>