options:
    type: INNODB
    collate: utf8_general_ci
    charset: utf8
Admin:
  connection: doctrine
  tableName: admin
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(11)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    password:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
Language:
  tableName: language
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(55)
      unique: true
    lang:
      type: string(2)
      unique: true
    is_default:
      type: boolean
      default: 0
    is_active:
      type: boolean
      default: 1
    flag:
      type: string(55)
  actAs:
    Timestampable: true
Variable:
  tableName: variable
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
    value:
      type: text
    is_active:
      type: boolean
      default: 1
  actAs:
    Timestampable: true
    I18n:
      fields: [value]
Category:
  actAs:
    Timestampable: ~
    I18n:
      fields: [name]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(100)
      notnull: true
    image_name:
      type: string(100)
      notnull: false
    is_active:
      type: boolean
      default: 1
    parentid:
      type: integer(4)
      notnull: true
    level:
      type: integer(4)
      notnull: true
    site_id:
      type: integer(4)
      notnull: true
    banner_image:
      type: string(100)
      notnull: false
    is_promote:
      type: boolean
Country:
  tableName: country
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(100)
      notnull: true
    is_active:
      type: boolean
      default: 1
  actAs:
    Timestampable: true
    I18n:
      fields: [name]
City:
  tableName: city
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    country_id:
      type: integer(4)
      notnull: true
    name:
      type: string(100)
      notnull: true
    is_active:
      type: boolean
      default: 1
  actAs:
    Timestampable: true
    I18n:
      fields: [name]